image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - npm ci --production
    - npm run build
    - ls _dist/
  artifacts:
    paths:
      - _dist/

deploy-job:
  image: "python:latest"
  stage: deploy
  environment: production
  dependencies:
    - build-job
  before_script:
    - pip install awscli
  script:
    - echo "Deploying application..."
    - aws s3 cp _dist/ s3://amsat-web-static/ --recursive
