name: Deploy

concurrency:
  group: deploy
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main,]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout the repo
        uses: actions/checkout@v3

      - id: install-node
        name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - id: install-npm
        name: Use npm v7
        run: npm install --global npm@7

      - id: cache-node-modules
        name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - id: install-project-modules
        name: Install project dependencies
        run: npm ci --production   ## For the app's build routine

      - id: npm-build
        name: Build project distribution
        run: npm run build
        env:
          BAKER_PATH_PREFIX: /amsat-satellite-index/

      - id: commit
        name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git pull origin $GITHUB_REF
          git add ./docs
          git commit -m "Added latest ETL" --author="palewire <palewire@users.noreply.github.com>" && git push || true
        shell: bash
